consul:
    hostname: consul
    container_name: consul
    image: qnib/alpn-consul
    environment:
     - DC_NAME=dc1
     - RUN_SERVER=true
     - BOOTSTRAP_CONSUL=true
    ports:
     - "8500:8500"
    dns: 127.0.0.1

influxdb:
    hostname: influxdb
    container_name: influxdb
    dns: 127.0.0.1
    image: qnib/influxdb
    volumes: 
    - /opt/influxdb/shared
    environment:
    - DC_NAME=dc1
    - COLLECT_METRICS=false
    - INFLUXDB_GRAPHITE_ENABLED=true
    links:
    - consul:consul
    ports:
    - 2003:2003
    - 8083:8083
    - 8086:8086

grafana2:
    image: qnib/grafana2
    container_name: grafana2
    ports:
     - "3000:3000"
    dns: 127.0.0.1
    hostname: grafana
    environment:
    - DC_NAME=dc1
    - COLLECT_METRICS=false
    links:
    - consul:consul
